export const ADMIN_DASHBOARD_MODE_CREATE = "ADMIN_DASHBOARD_MODE_CREATE"
export const ADMIN_DASHBOARD_MODE_READ = "ADMIN_DASHBOARD_MODE_READ"
export const ADMIN_DASHBOARD_MODE_UPDATE = "ADMIN_DASHBOARD_MODE_UPDATE"